### ISSUE TITLE
Announcement not working.

### ISSUE THREAD

**Issue by didacus** [MaxToyberman/react-native-accessibility#1]
Hi guys, I am trying to use this library without success. I am trying to read the announcement every time a button is pressed. What am I doing wrong? Thank you in advance.

Button:
```
                <TouchableOpacity
                style={styles.button}
                accessible={true}
                accessibilityLabel={'Tap me!'}
                onPress={this._onPress}
                >
                    <View>
                        <Text>Press me!</Text>
                    </View>
                </TouchableOpacity>
```

Function:

```
    _onPress = () => {
        announceForAccessibility('type some message here')
        console.log("Button pressed!")
    }
```

**Comment by MaxToyberman** [comment]
Hi @didacus , can you show me your import statement ? , what device are you using ?

**Comment by didacus** [comment]
@MaxToyberman thank you for the reply. After installing the library as described in the repository, I am importing it with `import { announceForAccessibility, focusOnView } from 'react-native-accessibility';`. At the moment I am using an iPhone 6. Can you see anything missing from the code I posted? Do I need to create a `ref` for the function?

**Comment by MaxToyberman** [comment]
@didacus do you have any errors ? do you have libRNReactNativeAccessibility.a in your build phases ? did you enable screen reader ?

**Comment by didacus** [comment]
There are no errors @MaxToyberman. The screen reader is activated as I can trigger it by swiping with two fingers. The issue might lie with  `libRNReactNativeAccessibility.a`. I don't think I have linked it `doh`. Where can I find it? It doesn't seem to be in the repo.

**Comment by MaxToyberman** [comment]
@didacus  did you run `react-native link react-native-accessibility` ?

**Comment by didacus** [comment]
Yes, I have @MaxToyberman

**Comment by didacus** [comment]
@MaxToyberman all is linked now. Including the `libRNReactNativeAccessibility.a` (manage to find it now). There are no errors, neither on console or Xcode. I wondering if there is something to do with `ref — focusOnView(this.refs.someRef)` Is the focus option only needed for focus interactions?  Do I also need it for the function above? By the way, do you have a working example?

**Comment by MaxToyberman** [comment]
@didacus  `announceForAccessibility` works now ?

**Comment by MaxToyberman** [comment]
`announceForAccessibility` is only used to announce messages (text) you choose, `focusOnView`  focuses on a view , the two function are not related.

**Comment by didacus** [comment]
Unfortunately not working yet. I am trying to create a clean app. Bare with me.

**Comment by didacus** [comment]
@MaxToyberman, unfortunately, I can't make it work. I appreciate your help though. Just to clarify. This library would allow me to trigger announcements based on the string provided, correct?

**Comment by MaxToyberman** [comment]
@didacus  correct, this is one of the features. did you check it on android ?

**Comment by MaxToyberman** [comment]
@didacus if you can provide me a link to the project, i will check it.

**Comment by didacus** [comment]
Thank you in advance @MaxToyberman , the link for the project is here — [Accessibility]. I have created a fresh project but still does not work. (https://github.com/didacus/Accessibility)

**Comment by MaxToyberman** [comment]
@didacus  i will let you know later, as soon as possible :)

**Comment by MaxToyberman** [comment]
@didacus I think something is wrong with your yarn.lock file remove it and yarn install again.
it doesn't contain react-native-accessibility

**Comment by MaxToyberman** [comment]
@didacus  it works for me, please let me know

**Comment by didacus** [comment]
@MaxToyberman just to clarify. Is it working for you after you dealt with the yarn.lock or straight out of GitHub? Also, are you recommending me to re-install yarn or are you referring to react-native-accessibility?

**Comment by MaxToyberman** [comment]
@didacus I have Issued a pull request to you ,https://github.com/didacus/Accessibility/pull/1
please check it and tell me if it works now . if it works I will explain what was the problem

**Comment by didacus** [comment]
@MaxToyberman I just merged you commit but still does not work. I am puzzled. I wonder if its something to do with the accessibility settings on the phone (iPhone 6). I have active Speech > Speak Screen. Do I need to have any other option active for this to work?

**Comment by MaxToyberman** [comment]
@didacus can you check if `announceForAccessibility` is undefined  ?

**Comment by MaxToyberman** [comment]
@didacus you need to enable voiceover  ?
 
you can find it here https://www.imore.com/how-use-voiceover-iphone-and-ipad#activate

1.Launch the Settings app from your Home screen.
2.Tap on General.
3.Tap on Accessibility.
4.Tap on VoiceOver under the Vision category at the top
5.Tap the VoiceOver switch to enable it.

**Comment by didacus** [comment]
@MaxToyberman it seems that `announceForAccessibility` is undefined.

```
console.log("announceForAccessibility", typeof announceForAccessibility('This is a message announcement using Max\'s library'))
// Output: announceForAccessibility undefined
```
No, I do not need VoiceOver enabled. I just wanted to make sure the library does not need it.

**Comment by MaxToyberman** [comment]
@didacus  please follow my instructions:
1) choose your project from 'project navigator'
2)open Build Phases and expand Link Binary with Libraries
3) in you r project navigator  expand RNReactNativeAccessibility -> Products
4) drag RNReactNativeAccessibility.a to Link Binary with Libraries from step 2

**Comment by MaxToyberman** [comment]
@didacus  ![screen shot 2018-03-15 at 13 24 09](https://user-images.githubusercontent.com/11058371/37460551-31b6098a-2854-11e8-8d75-0b983405c054.png)

**Comment by didacus** [comment]
@MaxToyberman The library is already there, but I did it once more. Built the app again, no success.
https://cl.ly/452n3y1j2K07

**Comment by MaxToyberman** [comment]
@didacus this is very strange.  I will check it once again

**Comment by MaxToyberman** [comment]
@didacus  I don't understand just one thing, how do you want to test it without voiceover ?

**Comment by didacus** [comment]
I appreciate the help @MaxToyberman For now, I only need to make speech announcements based on certain conditions. The idea is to trigger the announcements without user interaction.

**Comment by MaxToyberman** [comment]
@didacus everything is working for me, this is very strange
